name: tutorial_metadetect
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - scipy
  - numba
  - pyyaml
  - sep
  - ngmix
  - metadetect
  - meds
  - des-sxdes
  - astropy
  - galsim
  - jupyter
  - jupyterlab
  - tqdm
  - joblib
  - s3fs
  - matplotlib
